# Generated by Django 4.1.5 on 2023-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('plane_name', models.CharField(max_length=20)),
                ('plane_code', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=20)),
                ('origin_airport', models.CharField(max_length=64)),
                ('origin_code', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=20)),
                ('destination_code', models.CharField(max_length=10)),
                ('destination_airport', models.CharField(max_length=64)),
                ('depart_time', models.TimeField(blank=True)),
                ('arrival_time', models.TimeField(blank=True)),
                ('economy_fare', models.FloatField(null=True)),
                ('business_fare', models.FloatField(null=True)),
                ('first_fare', models.FloatField(null=True)),
            ],
        ),
    ]
