# Generated by Django 4.1.5 on 2023-01-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyhigh', '0002_flight_flight_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_duration',
        ),
    ]
