# Generated by Django 4.1.5 on 2023-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyhigh', '0003_remove_flight_flight_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_duration',
            field=models.CharField(default='', max_length=20),
        ),
    ]
