# Generated by Django 4.1.5 on 2023-01-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyhigh', '0004_flight_flight_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=2)),
                ('country_code', models.CharField(max_length=10)),
                ('mob_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('amount', models.ImageField(max_length=10, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('flight_d_date', models.CharField(max_length=30)),
                ('flight_a_date', models.CharField(max_length=30)),
                ('flight_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyhigh.flight')),
            ],
        ),
    ]
