# Generated by Django 4.1.5 on 2023-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyhigh', '0008_rename_contact_details_booking_passengar_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
