# Generated by Django 4.1.5 on 2023-01-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyhigh', '0009_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_flight_a_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_flight_d_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
