# Generated by Django 4.1.5 on 2023-02-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyhigh', '0010_booking_return_flight_a_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('bookinginfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyhigh.booking')),
            ],
        ),
    ]
