# Generated by Django 4.1.5 on 2023-02-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyhigh', '0011_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='my_User',
        ),
    ]
