# Generated by Django 4.1.5 on 2023-02-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyhigh', '0012_rename_user_my_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_User',
            new_name='Userdetails',
        ),
    ]
