# Generated by Django 4.1.5 on 2023-02-02 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flyhigh', '0013_rename_my_user_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
